"""new models

Revision ID: 340dcff13a9f
Revises: 501e643a7bac
Create Date: 2023-04-28 13:41:56.170571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340dcff13a9f'
down_revision = '501e643a7bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walk')
    op.drop_table('post')
    op.drop_table('follow')
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_table('review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('walk_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.FLOAT(), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_review_user_id_user'),
    sa.ForeignKeyConstraint(['walk_id'], ['walk.id'], name='fk_review_walk_id_walk'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('profile_photo', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='fk_comment_post_id_post'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_comment_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('follower_id', sa.INTEGER(), nullable=False),
    sa.Column('followed_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='fk_follow_followed_id_user'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='fk_follow_follower_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_post_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('walk',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=120), nullable=False),
    sa.Column('distance', sa.FLOAT(), nullable=False),
    sa.Column('photo', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_walk_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
