"""Allow NULL for walk_id in reviews table

Revision ID: 579a6eb6551c
Revises: 8cda3bf252cc
Create Date: 2023-05-07 13:04:29.393124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579a6eb6551c'
down_revision = '8cda3bf252cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('walk_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('walk_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
