"""please work

Revision ID: a8c5f482bab6
Revises: a0488d899b0d
Create Date: 2023-04-29 15:11:46.160204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c5f482bab6'
down_revision = 'a0488d899b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('followed_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_follows_followed_id_users'), 'users', ['followed_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_follows_follower_id_users'), 'users', ['follower_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_follows_follower_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_follows_followed_id_users'), type_='foreignkey')
        batch_op.drop_column('followed_id')
        batch_op.drop_column('follower_id')

    # ### end Alembic commands ###
